version: "3.8"
services:

  produit:
    container_name: event_management
    ports:
      - "8082:8082"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/devops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped
    depends_on:
      - docker-mysql

  docker-mysql:
    image: "mysql:5.6"
    container_name: db_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=devops
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
    restart: unless-stopped